import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Footer } from "../components/shared/footer";
import Header from "@/components/shared/header";
import WhatsAppButton from "@/components/shared/whatsapp";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Rahatutzamanr rizon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Header></Header>
        {children}
        <WhatsAppButton 
        phoneNumber="01771276400"  // Replace with your WhatsApp number
        message="Hi! I'm interested in your services"  // Optional custom message
      />
      <Footer></Footer>
      </body>
    </html>
  );
}
